import os
import re
import gzip
import subprocess
import sys

def main():
    print("Building Web UI...")
    current_dir = os.path.dirname(os.path.abspath(__file__))
    webui_dir = os.path.join(current_dir, "webui")
    
    # Run npm run build in the webui folder
    try:
        subprocess.run(["npm", "run", "build"], cwd=webui_dir, check=True)
    except subprocess.CalledProcessError as e:
        print(f"Error running npm run build: {e}", file=sys.stderr)
        sys.exit(1)

    dist_dir = os.path.join(webui_dir, "dist")
    
    # Read built index.html
    index_html_path = os.path.join(dist_dir, "index.html")
    if not os.path.exists(index_html_path):
        print(f"Error: {index_html_path} does not exist", file=sys.stderr)
        sys.exit(1)
        
    with open(index_html_path, "r", encoding="utf-8") as f:
        html = f.read()

    # Read and decompress app.js.gz
    app_js_gz_path = os.path.join(dist_dir, "app.js.gz")
    if not os.path.exists(app_js_gz_path):
        print(f"Error: {app_js_gz_path} does not exist", file=sys.stderr)
        sys.exit(1)
        
    with gzip.open(app_js_gz_path, "rb") as f:
        js = f.read().decode("utf-8")

    # Read and decompress style.css.gz
    style_css_gz_path = os.path.join(dist_dir, "style.css.gz")
    if not os.path.exists(style_css_gz_path):
        print(f"Error: {style_css_gz_path} does not exist", file=sys.stderr)
        sys.exit(1)
        
    with gzip.open(style_css_gz_path, "rb") as f:
        css = f.read().decode("utf-8")

    # Inline JS: find the script tag matching app.js (possibly with cache buster query)
    html = re.sub(
        r'<script type="module" crossorigin src="\./app\.js[^"]*"></script>',
        lambda m: f'<script type="module">{js}</script>',
        html
    )

    # Inline CSS: find the style/link tag matching style.css (possibly with cache buster query)
    html = re.sub(
        r'<link rel="stylesheet" crossorigin href="\./style\.css[^"]*">',
        lambda m: f'<style>{css}</style>',
        html
    )

    # Force isDev to false for production
    html = html.replace("const isDev = true;", "const isDev = false;")

    # Gzip the final inlined HTML
    inlined_html_bytes = html.encode("utf-8")
    gzipped_html = gzip.compress(inlined_html_bytes)

    # Generate C header content
    header_path = os.path.join(current_dir, "main", "index_html.h")
    
    # Format bytes as hex array formatted with line breaks for readability
    c_bytes_list = [f"0x{b:02x}" for b in gzipped_html]
    c_bytes_formatted = ""
    for i in range(0, len(c_bytes_list), 12):
        chunk = ", ".join(c_bytes_list[i:i+12])
        c_bytes_formatted += f"    {chunk},\n"
    
    # Trim the trailing comma and newline
    c_bytes_formatted = c_bytes_formatted.rstrip(",\n")

    with open(header_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by web_builder.py. Do not edit. */\n")
        f.write("#pragma once\n\n")
        f.write("const unsigned char index_html_gz[] = {\n")
        f.write(c_bytes_formatted)
        f.write("\n};\n\n")
        f.write(f"const unsigned int index_html_gz_len = {len(gzipped_html)};\n")

    print(f"Web UI build completed. Generated {header_path} ({len(gzipped_html)} bytes gzipped).")

if __name__ == "__main__":
    main()
